name: UnityStreet
favicon: null
layout_spectrum: 0.476151
typography_spectrum: 0.080592
title: Welcome to Unity Street
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#1479ec'
    - '#cdcdcd'
    - '#8b8b8b'
  brandStrength: 0.986842
  lightness: 0.594572
  saturation: 0.671052
  rhythmicContrast: 0.1875
purpose: []
