analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#1479ec'
    - '#cdcdcd'
    - '#8b8b8b'
  brandStrength: 0.986842
  lightness: 0.594572
  rhythmicContrast: 0.1875
  saturation: 0.671052
cta: {}
layout_spectrum: 0.476151
name: UnityStreet
opengraph: {}
purpose: []
typography_spectrum: 0.080592
