name: UnityStreet
favicon: null
layout_spectrum: 0.3584347984287888
typography_spectrum: 0.8368158866651356
title: Unity Street
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07883858657442033
  lightness: 0.6373465845827013
  saturation: 0.2154739371035248
  rhythmicContrast: 0.449335306417197
purpose: []
