name: UnityStreet
favicon: null
layout_spectrum: 0.28304
typography_spectrum: 0.00156
title: Unity Street
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#1479ec'
    - '#cdcdcd'
    - '#8b8b8b'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
